SELECT D.STATUS "STATUS", D.TABLESPACE_NAME "NOME", D.CONTENTS "TIPO", D.EXTENT_MANAGEMENT "GERENCIAMENTO DE EXTENSÃO",
 TO_CHAR(NVL(A.BYTES / 1024 / 1024, 0),'99G999G990D900') "TAMANHO (M)", TO_CHAR(NVL(NVL(F.BYTES, 0), 0)/1024/1024 ,'99G999G990D900') "LIVRE (MB)",
 TO_CHAR(NVL((NVL(F.BYTES, 0)) / A.BYTES * 100, 0), '990D00') "% LIVRE" FROM SYS.DBA_TABLESPACES D, (SELECT TABLESPACE_NAME, SUM(BYTES) BYTES 
 FROM DBA_DATA_FILES GROUP BY TABLESPACE_NAME) A, (SELECT TABLESPACE_NAME, SUM(BYTES) BYTES FROM DBA_FREE_SPACE GROUP BY TABLESPACE_NAME) F 
 WHERE D.TABLESPACE_NAME = A.TABLESPACE_NAME(+) AND D.TABLESPACE_NAME = F.TABLESPACE_NAME(+) AND NOT (D.EXTENT_MANAGEMENT LIKE 'LOCAL' 
 AND D.CONTENTS LIKE 'TEMPORARY') UNION ALL SELECT D.STATUS "STATUS", D.TABLESPACE_NAME "NOME", D.CONTENTS "TIPO", 
 D.EXTENT_MANAGEMENT "GERENCIAMENTO DE EXTENSÃO", TO_CHAR(NVL(A.BYTES / 1024 / 1024, 0),'99G999G990D900') "TAMANHO (M)", 
 TO_CHAR(NVL((A.BYTES-T.BYTES), A.BYTES)/1024/1024,'99G999G990D900') "LIVRE (MB)",
 TO_CHAR(NVL((A.BYTES-T.BYTES) / A.BYTES * 100, 100), '990D00') "% LIVRE" 
 FROM SYS.DBA_TABLESPACES D, (SELECT TABLESPACE_NAME, SUM(BYTES) BYTES 
 FROM DBA_TEMP_FILES GROUP BY TABLESPACE_NAME) A, (SELECT TABLESPACE_NAME, 
 SUM(BYTES_CACHED) BYTES FROM V$TEMP_EXTENT_POOL GROUP BY TABLESPACE_NAME) T 
 WHERE D.TABLESPACE_NAME = A.TABLESPACE_NAME(+) AND D.TABLESPACE_NAME = T.TABLESPACE_NAME(+) 
 AND D.EXTENT_MANAGEMENT LIKE 'LOCAL' AND D.CONTENTS LIKE 'TEMPORARY'; 
